services:
  - redis-server

language: rust
rust:
  - nightly
  - beta
  - stable

matrix:
  allow_failures:
    - rust: nightly
    - rust: beta

script:
  - cargo test -v

notifications:
  email:
    on_success: change
    on_failure: always
