[package]
name = "maman"
version = "0.1.0"
authors = ["Laurent Arnoud <laurent@spkdev.net>"]
description = "Rust Web Crawler"
repository = "https://github.com/spk/maman.git"
homepage = "https://github.com/spk/maman"
keywords = ["web", "crawler", "spider"]
license = "MIT"
readme = "README.md"

[dependencies]
hyper = "0.9"
html5ever = "0.5"
tendril = "0.2"
string_cache = "0.2"
url = "1.0"
redis = "0.5"
rustc-serialize = "0.3"
time = "0.1"
rand = "0.3"
